[ctrl]
     print_level =              1
     xc =                       "x3lyp"
     basis_path =               "../../../basis-set-pool/cc-pVQZ"
     basis_type =               "spheric"
     eri_type =                 "ri-v"
     auxbas_path =              "../../../basis-set-pool/def2-SV(P)-JKFIT"
     auxbas_type =              "spheric"
     chkfile =                  "none"
     charge =                   0.0
     spin =                     1.0
     spin_polarization =        false
     pruning =                  "nwchem"
     radial_grid_method =       "treutler"
     external_grids =           "none"
     mixer =                    "diis"
     num_max_diis =             8
     start_diis_cycle =         1
     mix_param =                0.8
     max_scf_cycle =            100
     scf_acc_rho =              1.0e-5
     scf_acc_eev =              1.0e-5
     scf_acc_etot =             1.0e-8
     num_threads =              6
[geom]
     name =  "H, example"
     unit =  "Angstrom"
     position =[
             "H   0.0000000000      0.0000000000      0.0000000000",
             "H   0.7600000000      0.0000000000      0.0000000000"
     ]

