on: [push, pull_request]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: |
            cd ..
            curl -o rustup-init https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
            chmod +x rustup-init
            ./rustup-init -y
            curl -o Cargo.toml -L "https://github.com/igor-1982/rest_workspace/blob/master/Cargo.toml?raw=true"
            cat Cargo.toml
            curl -L "https://github.com/pyscf/pyscf-build-deps/blob/master/pyscf-2.2.1-deps.tar.gz?raw=true" | tar xzf -
            sudo apt-get update -qy 
            sudo apt-get install libhdf5-dev libopenblas-dev gcc gfortran -qy
            ls /usr/lib/x86_64-linux-gnu
            ls -l deps
            export REST_FORTRAN_COMPILER="gfortran"
            export REST_CINT_DIR=`pwd`/deps
            export REST_EXT_DIR=`pwd`/deps
            export REST_BLAS_DIR=`pwd`/deps
            export REST_HDF5_DIR=/usr/lib
            export REST_XC_DIR=`pwd`/deps
            git@github.com:igor-1982/rest_tensors.git
            git@github.com:igor-1982/rest_libcint.git
            cargo build
